apiVersion: v1
kind: Service
metadata:
  name: pflex-exporter
  labels:
    app.kubernetes.io/name: pflex-exporter
spec:
  selector:
    app.kubernetes.io/name: pflex-exporter
  ports:
    - name: metrics
      port: 2113
      targetPort: metrics
